/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package timbangantruckindahjaya;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import timbangantruckindahjaya.modul.mod_login;

import timbangantruckindahjaya.setting.Md5;

/**
 *
 * @author taufiq
 */
public class loginForm extends javax.swing.JFrame {

    /**
     * Creates new form loginForm
     */
    private final mod_login modulLogin;
    
    private Md5 md = new Md5();
    
    public loginForm() 
    {        
        this.modulLogin = new mod_login();
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        cmdLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmdSetting = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        txtPassword.setName("txtPassword"); // NOI18N

        txtUsername.setName("txtUsername"); // NOI18N

        cmdLogin.setText("Login");
        cmdLogin.setName("cmdogin"); // NOI18N
        cmdLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLoginActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Bermasalah dengan aplikasi timbangan? Hub. Taufiq Ext 383");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword)
                    .addComponent(txtUsername)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmdLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timbangantruckindahjaya/images/app.png"))); // NOI18N

        cmdSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timbangantruckindahjaya/images/setting.png"))); // NOI18N
        cmdSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSettingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLoginActionPerformed
        // TODO add your handling code here:
        //        javax.swing.JOptionPane.showMessageDialog(null, "ok","oke deh",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        if(modulLogin.open()==null)
        {
            int x = JOptionPane.showConfirmDialog(null, "Koneksi ke database tidak bisa.\nAplikasi akan segera ditutup!!!", "Perhatian",JOptionPane.CLOSED_OPTION ,JOptionPane.ERROR_MESSAGE);
            
            if(x==JOptionPane.OK_OPTION)  
            {
                System.exit(0);
            }
        }
        
        String username = this.txtUsername.getText(),
        password = String.valueOf(this.txtPassword.getPassword());

        
        int iLogin = modulLogin.is_user(username, password);

        if(iLogin > 0)
        {
            //            JOptionPane.showMessageDialog(null, "Data Ada cing ", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);

            Session.User = new User();
            Session.User.setUserId(iLogin);

            new timbangantruckindahjaya.func.Log().InsertLog("LOGIN", "Login userid="+iLogin);

            new masterTimbang(String.valueOf(iLogin)).setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Username atau Password salah ", "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cmdLoginActionPerformed

    private void cmdSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSettingActionPerformed
        // TODO add your handling code here:
        String password = "26a1b378c7b389a396764d08b4ced9ff";
        
        javax.swing.JLabel PLabel = new javax.swing.JLabel("Password");
        javax.swing.JPasswordField TxtPass = new javax.swing.JPasswordField();
        Object[] obj = {PLabel, TxtPass};
        //String data = JOptionPane.showInputDialog(null, "Silakan Masukkan Password Setting","Setting Auth",JOptionPane.OK_CANCEL_OPTION);
        int ConfReply = JOptionPane.showConfirmDialog(null, obj, "Setting Auth", JOptionPane.OK_CANCEL_OPTION);
        
        try 
        {
            if(ConfReply==JOptionPane.OK_OPTION)
            {
                if(md.StringEncrypt(String.valueOf(TxtPass.getPassword()).trim()).equals(password))
                {
                    new FormSetting().setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Password Salah!!!","Perhatian",JOptionPane.WARNING_MESSAGE);
                }
            }
        } catch (Exception ex) 
        {
            Logger.getLogger(loginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdSettingActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdLogin;
    private javax.swing.JButton cmdSetting;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
