/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package timbangantruckindahjaya;

import javax.swing.JOptionPane;
import timbangantruckindahjaya.modul.mod_user;

/**
 *
 * @author taufiq
 */
public class rubahPassword extends javax.swing.JDialog {

    /**
     * Creates new form loginForm
     */
    public rubahPassword() {        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmdChange = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPassLama = new javax.swing.JPasswordField();
        txtPassNew = new javax.swing.JPasswordField();
        txtRetypePass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rubah Password");
        setResizable(false);

        jLabel1.setText("Password Lama");

        jLabel2.setText("Password Baru");

        cmdChange.setText("Rubah Password");
        cmdChange.setName("cmdogin"); // NOI18N
        cmdChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdChangeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Bermasalah dengan aplikasi timbangan? Hub. Taufiq Ext 383");

        jLabel5.setText("Ulangi Password");

        txtPassLama.setName("txtPassword"); // NOI18N

        txtPassNew.setName("txtPassNew"); // NOI18N

        txtRetypePass.setName("txtPassword"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(jLabel4))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassNew)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmdChange)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtRetypePass)
                    .addComponent(txtPassLama)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRetypePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(cmdChange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timbangantruckindahjaya/images/app.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdChangeActionPerformed
        // TODO add your handling code here:
        //        javax.swing.JOptionPane.showMessageDialog(null, "ok","oke deh",javax.swing.JOptionPane.INFORMATION_MESSAGE);
//        String username = this.txtUsername.getText(),
//        password = String.valueOf(this.txtPassNew.getPassword());
//
        mod_user modulUser = new mod_user();
//
//        int iLogin = modulLogin.is_user(username, password);
//
//        if(iLogin > 0)
//        {
//            //            JOptionPane.showMessageDialog(null, "Data Ada cing ", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
//            this.setVisible(false);
//
//            Session.User = new User();
//            Session.User.setUserId(iLogin);
//
//            new timbangantruckindahjaya.func.Log().InsertLog("LOGIN", "Login userid="+iLogin);
//
//            new masterTimbang(String.valueOf(iLogin)).setVisible(true);
//        }
//        else
//        {
//            JOptionPane.showMessageDialog(null, "Username atau Password salah ", "Gagal", JOptionPane.WARNING_MESSAGE);
//        }
        String pass1 = String.valueOf(this.txtPassLama.getPassword()).trim(),
               pass2 = String.valueOf(this.txtPassNew.getPassword()).trim(),
               retype = String.valueOf(this.txtRetypePass.getPassword()).trim();
        
        if(pass1.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Password lama harus diisi!!!","Perhatian",JOptionPane.WARNING_MESSAGE);
            return;
        }
        else if(pass2.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Password Baru harus diisi!!!","Perhatian",JOptionPane.WARNING_MESSAGE);
            return;
        }
        else if(retype.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Isian Ulangi Password harus diisi!!!","Perhatian",JOptionPane.WARNING_MESSAGE);
            return;
        }
        else if(modulUser.CheckPassword(pass1)==false)
        {
            JOptionPane.showMessageDialog(null, "Password lama tidak sesuai!!!","Perhatian",JOptionPane.WARNING_MESSAGE);
            return;
        }
        else if(!pass2.equals(retype))
        {
            JOptionPane.showMessageDialog(null, "Password baru tidak sama dengan password ulangi!!!","Perhatian",JOptionPane.WARNING_MESSAGE);
            return;
        }
        else
        {
            if(modulUser.updatePassword(pass2)==true)
            {
                JOptionPane.showMessageDialog(null, "Password berhasil dirubah","Informasi",JOptionPane.INFORMATION_MESSAGE);
                
                this.dispose();
            }
            else
                JOptionPane.showMessageDialog(null, "Password tidak berhasil dirubah","Warning",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_cmdChangeActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdChange;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassLama;
    private javax.swing.JPasswordField txtPassNew;
    private javax.swing.JPasswordField txtRetypePass;
    // End of variables declaration//GEN-END:variables
}
